# Lister toutes les agences
LISTER_AGENCES = """
SELECT ID_AGE, NOM_AGE, VILLE, ADRESSE, TELEPHONE, EMAIL FROM AGENCES ORDER BY NOM_AGE;
"""
# Rechercher une agence par nom, ville ou adresse
RECHERCHER_AGENCE = """
SELECT * FROM AGENCES 
WHERE NOM_AGE LIKE ? OR VILLE LIKE ? OR ADRESSE LIKE ?;
"""
# Récupérer une agence par ID
GET_AGENCE_PAR_ID = """
SELECT * FROM AGENCES WHERE ID_AGE = ?;
"""

# Lister tous les employés
LISTER_EMPLOYES = """
SELECT ID_EMP, NAS, NOM, PRENOM, SALAIRE, POSTE, ID_AGE 
FROM EMPLOYES 
ORDER BY NOM;
"""

# Rechercher un employé par NAS ou Nom
RECHERCHER_EMPLOYE = """
SELECT ID_EMP, NAS, NOM, PRENOM, SALAIRE, POSTE, ID_AGE 
FROM EMPLOYES 
WHERE NAS LIKE ? OR NOM LIKE ?
ORDER BY NOM;
"""