########################### AGENCES ###########################

# Lister toutes les agences
LISTER_AGENCES = """
SELECT ID_AGE, NOM_AGE, VILLE, ADRESSE, TELEPHONE, EMAIL FROM AGENCES ORDER BY ID_AGE;
"""
# Rechercher une agence par nom, ville ou adresse
RECHERCHER_AGENCE = """
SELECT * FROM AGENCES 
WHERE NOM_AGE LIKE ? OR VILLE LIKE ? OR ADRESSE LIKE ?;
"""
# Récupérer une agence par ID
GET_AGENCE_PAR_ID = """
SELECT * FROM AGENCES WHERE ID_AGE = ?;
"""

############################# EMPLOYES #############################

# Lister tous les employés
LISTER_EMPLOYES = """
SELECT ID_EMP, NAS, NOM, PRENOM, SALAIRE, POSTE, ID_AGE 
FROM EMPLOYES 
ORDER BY NOM;
"""

# Rechercher un employé par NAS ou Nom
RECHERCHER_EMPLOYE = """
SELECT ID_EMP, NAS, NOM, PRENOM, SALAIRE, POSTE, ID_AGE 
FROM EMPLOYES 
WHERE NAS LIKE ? OR NOM LIKE ?
ORDER BY NOM;
"""
# Récupérer une employe par ID
GET_EMPLOYE_PAR_ID = """
SELECT * FROM EMPLOYES WHERE ID_EMP = ?;
"""

############################# CLIENTS #############################

# Rechercher un client par nom, prénom ou permis de conduire
RECHERCHER_CLIENT = """
SELECT ID_CLIENT, NOM, PRENOM, VILLE, ADRESSE, PERMIS_COND, HIST_ACCIDENTS, EMAIL, TELEPHONE, CARTE_CRED 
FROM CLIENTS 
WHERE NOM LIKE ? OR PRENOM LIKE ? OR PERMIS_COND LIKE ? OR EMAIL LIKE ?;
"""

# Rechercher un client par nom, prénom ou permis de conduire
LISTER_CLIENTS = """
SELECT ID_CLIENT, NOM, PRENOM, ADRESSE, PERMIS_COND, HIST_ACCIDENTS, VILLE, EMAIL, TELEPHONE, CARTE_CRED 
FROM CLIENTS
"""

GET_CLIENT_PAR_ID = """
SELECT ID_CLIENT, NOM, PRENOM, VILLE, ADRESSE, PERMIS_COND, HIST_ACCIDENTS, EMAIL, TELEPHONE, CARTE_CRED
FROM CLIENTS
WHERE ID_CLIENT = ?
"""


############################# MARQUES #############################

# Lister toutes les marques
LISTER_MARQUES = """
SELECT ID_MARQ, MARQUE
FROM MARQUE_VEHIC
ORDER BY MARQUE;
"""

# Récupérer une marque par ID
GET_MARQUE_PAR_ID = """
SELECT ID_MARQ, MARQUE
FROM MARQUE_VEHIC
WHERE ID_MARQ = ?;
"""

# Rechercher une marque par nom (partiel ou complet)
RECHERCHER_MARQUE = """
SELECT ID_MARQ, MARQUE
FROM MARQUE_VEHIC
WHERE MARQUE LIKE ?;
"""

############################# MODELES #############################

# Récupérer un modèle par ID
GET_MODELE_PAR_ID = """
SELECT * FROM MODELE_VEHIC WHERE ID_MOD = ?;
"""

# Lister tous les modèles
GET_TOUT_MODELES = """
SELECT * FROM MODELE_VEHIC ORDER BY MODELE;
"""

# Rechercher un modèle par nom
RECHERCHER_MODELES = """
SELECT * FROM MODELE_VEHIC WHERE MODELE LIKE ? ORDER BY MODELE;
"""


############################# TYPE-VEHICULE #############################

# Récupérer un type par ID
GET_TYPE_VEHIC_PAR_ID = """
SELECT * FROM TYPE_VEHIC WHERE ID_TP_VEHIC = ?;
"""


# Lister tous les modèles
GET_TOUT_TYPE_VEHIC = """
SELECT * FROM TYPE_VEHIC ORDER BY TYPE_VEHIC;
"""

############################# VEHICULES #############################

#Récupérer un véhicule par ID
GET_VEHICULE_PAR_ID = """
SELECT F.ID_VEHIC, F.IMMATRICULATION, F.ANNEE_FAB, F.COULEUR, F.KM, 
       M.MARQUE, MO.MODELE, T.TYPE_VEHIC, F.TYPE_CARBUR, F.STATUS,
       A.NOM_AGE AS NOM_AGENCE
FROM FLOTTE F
JOIN MARQUE_VEHIC M ON F.ID_MARQ = M.ID_MARQ
JOIN MODELE_VEHIC MO ON F.ID_MOD = MO.ID_MOD
JOIN TYPE_VEHIC T ON F.ID_TP_VEHIC = T.ID_TP_VEHIC
JOIN DISPO_VEHICULE DV ON F.ID_VEHIC = DV.ID_VEHIC
JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
WHERE F.ID_VEHIC = ?
"""


#Lister tous les véhicules
LISTER_VEHICULES = """
SELECT v.ID_VEHIC, v.IMMATRICULATION, v.TYPE_CARBUR, v.ANNEE_FAB, v.COULEUR, v.STATUS, v.KM, m.MARQUE, mo.MODELE, t.TYPE_VEHIC
FROM FLOTTE v
JOIN MARQUE_VEHIC m ON v.ID_MARQ = m.ID_MARQ
JOIN MODELE_VEHIC mo ON v.ID_MOD = mo.ID_MOD
JOIN TYPE_VEHIC t ON v.ID_TP_VEHIC = t.ID_TP_VEHIC;
"""

#Lister les véhicules disponibles

LISTER_VEHICULES_DISPONIBLES = """
SELECT
F.ID_VEHIC,
	MQ.MARQUE,
	MD.MODELE,
    F.COULEUR,
    F.TYPE_CARBUR, 
	TP.TYPE_VEHIC,
    F.ANNEE_FAB, 
    F.IMMATRICULATION,
	DV.DISPON_STOCK,
	A.NOM_AGE
FROM dbo.FLOTTE AS F WITH (NOLOCK)
INNER JOIN 
dbo.DISPO_VEHICULE AS DV WITH (NOLOCK) ON 
F.ID_VEHIC = DV.ID_VEHIC
INNER JOIN MARQUE_VEHIC AS MQ WITH (NOLOCK) ON
F.ID_MARQ = MQ.ID_MARQ
INNER JOIN MODELE_VEHIC AS MD WITH (NOLOCK) ON
F.ID_MOD = MD.ID_MOD
INNER JOIN TYPE_VEHIC AS TP WITH (NOLOCK) ON
F.ID_TP_VEHIC = TP.ID_TP_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
WHERE 
DV.DISPON_STOCK = 'DISPONIBLE'
ORDER BY MQ.MARQUE, MD.MODELE;
"""

#Rechercher un véhicule par immatriculation ou modèle
RECHERCHER_VEHICULE = """
SELECT v.ID_VEHIC, v.IMMATRICULATION, v.TYPE_CARBUR, v.ANNEE_FAB, v.COULEUR, v.STATUS, v.KM, m.MARQUE, mo.MODELE, t.TYPE_VEHIC
FROM FLOTTE v
JOIN MARQUE_VEHIC m ON v.ID_MARQ = m.ID_MARQ
JOIN MODELE_VEHIC mo ON v.ID_MOD = mo.ID_MOD
JOIN TYPE_VEHIC t ON v.ID_TP_VEHIC = t.ID_TP_VEHIC
WHERE v.IMMATRICULATION LIKE ? OR mo.MODELE LIKE ?;
"""

############################# OPTIONS #############################

# Récupérer un optionnel par ID
GET_OPTIONNEL_PAR_ID = """
SELECT ID_OPTIO, NOM_OPTIO, PRIX_OPTIO_JOUR FROM OPTIONNELS WHERE ID_OPTIO = ?;
"""

# Lister tous les optionnels
LISTER_OPTIONNELS = """
SELECT * FROM OPTIONNELS ORDER BY NOM_OPTIO;
"""

# Rechercher un optionnel par nom
RECHERCHER_OPTIONNELS = """
SELECT * FROM OPTIONNELS WHERE NOM_OPTIO LIKE ? ORDER BY NOM_OPTIO;
"""


############################# TARIFICATIONS #############################

#Récupérer toutes les tarifications
LISTER_TARIFICATIONS = """
    SELECT t.ID_TARIF, t.KM_JOUR, t.PRIX_LOCAT_JOUR, v.TYPE_VEHIC
    FROM TARIFATION t
    JOIN TYPE_VEHIC v ON t.ID_TP_VEHIC = v.ID_TP_VEHIC
"""

#Rechercher une tarification spécifique
RECHERCHER_TARIFICATION = """
    SELECT t.ID_TARIF, t.KM_JOUR, t.PRIX_LOCAT_JOUR, v.TYPE_VEHIC
    FROM TARIFATION t
    JOIN TYPE_VEHIC v ON t.ID_TP_VEHIC = v.ID_TP_VEHIC
    WHERE v.TYPE_VEHIC LIKE ? OR t.KM_JOUR = ? OR t.PRIX_LOCAT_JOUR = ?
"""

#Récupérer une tarification par ID
GET_TARIF_PAR_ID = """
SELECT t.ID_TARIF, t.KM_JOUR, t.PRIX_LOCAT_JOUR, v.TYPE_VEHIC
FROM TARIFATION t
JOIN TYPE_VEHIC v ON t.ID_TP_VEHIC = v.ID_TP_VEHIC
WHERE t.ID_TARIF = ?
"""


############################# ASSURANCES #############################

GET_ASSURANCE_PAR_ID = """
SELECT ID_ASSURANCE, TYPE_ASSURANCE, PRIX_JOUR
FROM ASSURANCE
WHERE ID_ASSURANCE = ?;
"""

# Requête pour lister toutes les assurances
LISTER_ASSURANCES = """
SELECT ID_ASSURANCE, TYPE_ASSURANCE, PRIX_JOUR FROM ASSURANCE;
"""

# Requête pour rechercher une assurance par type
RECHERCHER_ASSURANCE = """
SELECT ID_ASSURANCE, TYPE_ASSURANCE, PRIX_JOUR 
FROM ASSURANCE 
WHERE TYPE_ASSURANCE LIKE ?;
"""

############################# MAINTENANCES #############################

# Récupérer une maintenance par ID
GET_MAINTENANCE_PAR_ID = """
SELECT * FROM MAINTENANCE WHERE ID_MAINTEN = ?;
"""

# Récupérer toutes les informations détaillées d’un véhicule (incluant l’agence) pour l’affichage dans le formulaire de maintenance
GET_INFO_VEHIC_MAINT = """
SELECT 
    A.NOM_AGE AS NOM_AGENCE,
    MQ.MARQUE,
    MD.MODELE,
    F.ANNEE_FAB AS ANNEE_FABRICATION,
    F.COULEUR,
    F.KM AS KILOMETRAGE,
    F.IMMATRICULATION,
    F.TYPE_CARBUR,
    TV.TYPE_VEHIC,
    F.STATUS
FROM FLOTTE F
INNER JOIN MARQUE_VEHIC MQ ON F.ID_MARQ = MQ.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
INNER JOIN TYPE_VEHIC TV ON F.ID_TP_VEHIC = TV.ID_TP_VEHIC
INNER JOIN DISPO_VEHICULE DV ON F.ID_VEHIC = DV.ID_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
WHERE F.ID_VEHIC = ?;
"""


# Lister toutes les maintenances
GET_TOUT_VEHICULES_MAINT = """
SELECT 
    F.ID_VEHIC,
    A.NOM_AGE AS NOM_AGENCE,
    MQ.MARQUE,
    MD.MODELE,
    F.ANNEE_FAB AS ANNEE_FABRICATION,
    F.COULEUR,
    F.KM AS KILOMETRAGE,
    F.IMMATRICULATION,
    F.TYPE_CARBUR,
    TV.TYPE_VEHIC,
    F.STATUS
FROM FLOTTE F
INNER JOIN MARQUE_VEHIC MQ ON F.ID_MARQ = MQ.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
INNER JOIN TYPE_VEHIC TV ON F.ID_TP_VEHIC = TV.ID_TP_VEHIC
INNER JOIN DISPO_VEHICULE DV ON F.ID_VEHIC = DV.ID_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
ORDER BY F.ID_VEHIC;
"""



# Récupérer toutes les informations détaillées d’un véhicule (incluant l’agence) pour l’affichage dans le formulaire de maintenance
GET_INFO_VEHIC_MAINT_BT_MAINT = """
SELECT 
    A.NOM_AGE AS NOM_AGENCE,
    MQ.MARQUE,
    MD.MODELE,
    F.ANNEE_FAB AS ANNEE_FABRICATION,
    F.COULEUR,
    F.KM AS KILOMETRAGE,
    F.IMMATRICULATION,
    F.TYPE_CARBUR,
    TV.TYPE_VEHIC,
    F.STATUS,
    M.DATE_MAINTEN,
	M.DATE_MAINTEN_FIN,
	M.TYPE_MAINTEN,
	M.ID_EMP,
	M.DESC_MAINTEN
FROM FLOTTE F
INNER JOIN MARQUE_VEHIC MQ ON F.ID_MARQ = MQ.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
INNER JOIN TYPE_VEHIC TV ON F.ID_TP_VEHIC = TV.ID_TP_VEHIC
INNER JOIN DISPO_VEHICULE DV ON F.ID_VEHIC = DV.ID_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
INNER JOIN MAINTENANCE M ON F.ID_VEHIC = M.ID_VEHIC
WHERE F.ID_VEHIC = ?;
"""


# Lister toutes les maintenances
GET_TOUT_VEHICULES_MAINT_BT_MAINT = """
SELECT 
    F.ID_VEHIC,
    A.NOM_AGE AS NOM_AGENCE,
    MQ.MARQUE,
    MD.MODELE,
    F.ANNEE_FAB AS ANNEE_FABRICATION,
    F.COULEUR,
    F.KM AS KILOMETRAGE,
    F.IMMATRICULATION,
    F.TYPE_CARBUR,
    TV.TYPE_VEHIC,
    F.STATUS,
    M.DATE_MAINTEN,
	M.DATE_MAINTEN_FIN,
	M.TYPE_MAINTEN,
	M.ID_EMP,
	M.DESC_MAINTEN
FROM FLOTTE F
INNER JOIN MARQUE_VEHIC MQ ON F.ID_MARQ = MQ.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
INNER JOIN TYPE_VEHIC TV ON F.ID_TP_VEHIC = TV.ID_TP_VEHIC
INNER JOIN DISPO_VEHICULE DV ON F.ID_VEHIC = DV.ID_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
INNER JOIN MAINTENANCE M ON F.ID_VEHIC = M.ID_VEHIC
WHERE F.STATUS = 'EN MAINTENANCE'
ORDER BY F.ID_VEHIC;
"""



# Rechercher une maintenance par type ou ID du véhicule
RECHERCHER_MAINTENANCE = """
SELECT * FROM MAINTENANCE
WHERE TYPE_MAINTEN LIKE ? OR (ISNUMERIC(?) = 1 AND ID_VEHIC = ?);
"""


############################# RESERVATIONS #############################

# Liste toutes les réservations
LISTER_RESERVATIONS = """
SELECT ID_RESERV, DATE_DEBUT, DATE_FIN, STATUS_RESER, DUREE_JOUR, ID_CLIENT, ID_VEHIC, ID_TARIF, ID_ASSURANCE, ID_OPTIO, PRIX_TOTAL
FROM RESERVATIONS
"""

# Récupère une réservation spécifique par ID
GET_RESERVATION_PAR_ID = """
SELECT ID_RESERV, DATE_DEBUT, DATE_FIN, STATUS_RESER, DUREE_JOUR, ID_CLIENT, ID_VEHIC, ID_TARIF, ID_ASSURANCE, ID_OPTIO, PRIX_TOTAL
FROM RESERVATIONS
WHERE ID_RESERV = ?
"""

# Recherche une réservation par ID_CLIENT, ID_VEHIC ou DATE_DEBUT
RECHERCHER_RESERVATION = """
SELECT ID_RESERV, DATE_DEBUT, DATE_FIN, STATUS_RESER, DUREE_JOUR, ID_CLIENT, ID_VEHIC, ID_TARIF, ID_ASSURANCE, ID_OPTIO, PRIX_TOTAL
FROM RESERVATIONS
WHERE CAST(ID_CLIENT AS TEXT) LIKE ? OR CAST(ID_VEHIC AS TEXT) LIKE ? OR DATE_DEBUT LIKE ?
"""

GET_RESERVATION_DETAILS_PAR_ID = """
SELECT 
    R.ID_RESERV,
    R.DATE_DEBUT,
    R.DATE_FIN,
    R.STATUS_RESER,
    R.DUREE_JOUR,
    R.ID_CLIENT,
    R.ID_VEHIC,
    R.ID_TARIF,
    R.ID_ASSURANCE,
    R.ID_OPTIO,
    C.NOM AS NOM_CLIENT,
    C.PRENOM AS PRENOM_CLIENT,
    C.ADRESSE AS ADRESSE_CLIENT,
    C.VILLE AS VILLE_CLIENT,
    C.TELEPHONE AS TELEPHONE_CLIENT,
    C.EMAIL AS EMAIL_CLIENT
FROM RESERVATIONS R
JOIN CLIENTS C ON R.ID_CLIENT = C.ID_CLIENT
WHERE R.ID_RESERV = ?
"""

