# queriesrapports.py

# Liste de tous les véhicules de la flotte, avec état et contrat actif
GET_FLOTTE_VEHICULES = """
SELECT DISTINCT F.ID_VEHIC, MV.MARQUE, MD.MODELE, TV.TYPE_VEHIC, F.TYPE_CARBUR, F.COULEUR, F.ANNEE_FAB, F.IMMATRICULATION, F.KM, F.STATUS AS STATUS_MAINTENANCE,
    COALESCE(
        (SELECT TOP 1 
		'CONTRAT EN COURS' 
         FROM RESERVATIONS R 
         WHERE R.ID_VEHIC = F.ID_VEHIC 
         AND R.STATUS_RESER = 'CONFIRMEE'
         ORDER BY R.DATE_DEBUT DESC),
        'AUCUN CONTRAT ACTIF'
    ) AS STATUS_RESERVATION
FROM FLOTTE F
INNER JOIN MARQUE_VEHIC MV ON F.ID_MARQ = MV.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
INNER JOIN TYPE_VEHIC TV ON F.ID_TP_VEHIC = TV.ID_TP_VEHIC
LEFT JOIN RESERVATIONS R ON F.ID_VEHIC = R.ID_VEHIC
ORDER BY F.ID_VEHIC
"""

# Liste de tous les clients impliqués dans des incidents impactant l'assurance
GET_CLIENTS_AVEC_INCIDENTS_ASSURANCE = """
SELECT DISTINCT CL.NOM, CL.PERMIS_COND, CL.HIST_ACCIDENTS
FROM CONTRACTS C
INNER JOIN RESERVATIONS R ON C.ID_RESERV = R.ID_RESERV
INNER JOIN CLIENTS CL ON R.ID_CLIENT = CL.ID_CLIENT
INNER JOIN INCIDENTS I ON C.ID_CONTRACT = I.ID_CONTRACT
WHERE I.TYPE_INCIDENT <> 'PANNE'
"""

# Liste de tous les véhicules ayant eu des incidents
GET_VEHICULES_AVEC_INCIDENTS = """
SELECT DISTINCT F.ID_VEHIC, MV.MARQUE, MD.MODELE, F.COULEUR, F.KM, F.ANNEE_FAB, COUNT (I.ID_INCIDENT) AS NUM_INCIDENTS
FROM FLOTTE F
INNER JOIN RESERVATIONS R ON F.ID_VEHIC = R.ID_VEHIC
INNER JOIN CONTRACTS C ON R.ID_RESERV = C.ID_RESERV
INNER JOIN INCIDENTS I ON C.ID_CONTRACT = I.ID_CONTRACT
INNER JOIN MARQUE_VEHIC MV ON F.ID_MARQ = MV.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
GROUP BY F.ID_VEHIC, MV.MARQUE, MD.MODELE, F.COULEUR, F.KM, F.ANNEE_FAB
"""

# Quantité de véhicules disponibles par agence selon le type de voiture
GET_VEHICULES_DISPONIBLES_PAR_AGENCE = """
SELECT A.NOM_AGE, TV.TYPE_VEHIC, DV.DISPON_STOCK, COUNT(F.ID_VEHIC) AS QUANTITE
FROM DISPO_VEHICULE DV
INNER JOIN FLOTTE F ON DV.ID_VEHIC = F.ID_VEHIC
INNER JOIN TYPE_VEHIC TV ON F.ID_TP_VEHIC = TV.ID_TP_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
WHERE DV.DISPON_STOCK = 'DISPONIBLE'
GROUP BY A.NOM_AGE, TV.TYPE_VEHIC, DV.DISPON_STOCK
ORDER BY A.NOM_AGE
"""

# État d'entretien des véhicules par agence et employé responsable
GET_ENTRETIEN_PAR_AGENCE = """
SELECT A.NOM_AGE, E.NOM, E.POSTE, MV.MODELE, M.TYPE_MAINTEN, M.STATUS_MAINT, CONVERT(DATE, M.DATE_MAINTEN) AS [DATE DEBUT MAINTENCE],
CONVERT(DATE, M.DATE_MAINTEN_FIN) AS [DATE FIN MAINTENCE],
DATEDIFF(DAY, M.DATE_MAINTEN, ISNULL(M.DATE_MAINTEN_FIN, GETDATE()))+1 AS JOUR_EN_REPAR
FROM MAINTENANCE M
INNER JOIN EMPLOYES E ON M.ID_EMP = E.ID_EMP
INNER JOIN AGENCES A ON E.ID_AGE = A.ID_AGE
INNER JOIN FLOTTE F ON M.ID_VEHIC = F.ID_VEHIC
INNER JOIN MODELE_VEHIC MV ON F.ID_MOD = MV.ID_MOD
"""

# Liste de tous les véhicules avec contrats actifs
GET_VEHICULES_CONTRATS_ACTIFS = """
SELECT 
    F.ID_VEHIC,
	CT.NOM AS [NOM CLIENT],
    MV.MARQUE, 
    MD.MODELE, 
    F.COULEUR, 
    F.IMMATRICULATION,
    E.NOM AS EMPLOYE_RESPONSABLE,
    C.DUREE_JOURS AS DUREE_CONTRAT_JOURS,
    A.TYPE_ASSURANCE,
    O.NOM_OPTIO AS OPTION_CHOISIE,
    C.PRIX_TOTAL AS PRIX_CONTRAT
FROM CONTRACTS C
INNER JOIN RESERVATIONS R ON C.ID_RESERV = R.ID_RESERV
INNER JOIN FLOTTE F ON R.ID_VEHIC = F.ID_VEHIC
INNER JOIN MARQUE_VEHIC MV ON F.ID_MARQ = MV.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
INNER JOIN EMPLOYES E ON C.ID_EMP = E.ID_EMP
INNER JOIN ASSURANCE A ON R.ID_ASSURANCE = A.ID_ASSURANCE
INNER JOIN CLIENTS CT ON R.ID_CLIENT = CT.ID_CLIENT
LEFT JOIN OPTIONNELS O ON R.ID_OPTIO = O.ID_OPTIO
WHERE C.STATUS_CONTRACT = 'EN COURS'
ORDER BY F.ID_VEHIC
"""

# Nombre de contrats avec incidents par employé responsable
GET_EMPLOYES_AVEC_INCIDENTS = """
SELECT 
    E.ID_EMP,
    E.NOM AS NOM_EMPLOYE, 
    E.POSTE,
    A.NOM_AGE AS AGENCE,
    COUNT(DISTINCT C.ID_CONTRACT) AS NOMBRE_CONTRATS_AVEC_INCIDENTS
FROM EMPLOYES E
INNER JOIN CONTRACTS C ON E.ID_EMP = C.ID_EMP
INNER JOIN INCIDENTS I ON C.ID_CONTRACT = I.ID_CONTRACT
INNER JOIN AGENCES A ON E.ID_AGE = A.ID_AGE
GROUP BY E.ID_EMP, E.NOM, E.POSTE, A.NOM_AGE
ORDER BY NOMBRE_CONTRATS_AVEC_INCIDENTS DESC
"""

# Nombre de réservations par agence pour le mois de janvier
GET_RESERVATIONS_PAR_AGENCE_JANVIER = """
SELECT 
    A.ID_AGE,
    A.NOM_AGE AS AGENCE,
    COUNT(R.ID_RESERV) AS NOMBRE_RESERVATIONS_JANVIER
FROM RESERVATIONS R
INNER JOIN FLOTTE F ON R.ID_VEHIC = F.ID_VEHIC
INNER JOIN DISPO_VEHICULE DV ON F.ID_VEHIC = DV.ID_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
WHERE MONTH(R.DATE_DEBUT) = 1
GROUP BY A.ID_AGE, A.NOM_AGE
ORDER BY NOMBRE_RESERVATIONS_JANVIER DESC
"""

# Nombre de contrats en cours par agence pour le mois de janvier
GET_CONTRATS_PAR_AGENCE_JANVIER = """
SELECT 
    A.ID_AGE,
    A.NOM_AGE AS AGENCE,
    COUNT(C.ID_CONTRACT) AS NOMBRE_CONTRATS_JANVIER
FROM CONTRACTS C
INNER JOIN RESERVATIONS R ON C.ID_RESERV = R.ID_RESERV
INNER JOIN FLOTTE F ON R.ID_VEHIC = F.ID_VEHIC
INNER JOIN DISPO_VEHICULE DV ON F.ID_VEHIC = DV.ID_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
WHERE 
    C.STATUS_CONTRACT = 'EN COURS' AND
    (
        MONTH(C.DATE_DEBUT) <= 1 AND MONTH(C.DATE_FIN) >= 1
    )
GROUP BY A.ID_AGE, A.NOM_AGE
ORDER BY NOMBRE_CONTRATS_JANVIER DESC
"""

# Facturation prévue et réalisée par agence et par mois
GET_FACTURATION_PAR_AGENCE_MOIS = """
SELECT 
    A.ID_AGE,
    A.NOM_AGE AS AGENCE,
    DATENAME(MONTH, C.DATE_DEBUT) AS MOIS,
    YEAR(C.DATE_DEBUT) AS ANNEE,
    SUM(C.PRIX_TOTAL) AS TOTAL_FACTURE,
    ISNULL((
        SELECT SUM(R2.PRIX_TOTAL)
        FROM RESERVATIONS R2
        INNER JOIN FLOTTE F2 ON R2.ID_VEHIC = F2.ID_VEHIC
        INNER JOIN DISPO_VEHICULE DV2 ON F2.ID_VEHIC = DV2.ID_VEHIC
        WHERE 
            R2.STATUS_RESER IN ('EN ATTENTE', 'CONFIRMEE')
            AND DV2.ID_AGE = A.ID_AGE
            AND MONTH(R2.DATE_DEBUT) = MONTH(C.DATE_DEBUT)
            AND YEAR(R2.DATE_DEBUT) = YEAR(C.DATE_DEBUT)
    ), 0) AS FACTURATION_PREVUE,
    SUM(CASE 
            WHEN R.DATE_FIN < GETDATE() THEN R.PRIX_TOTAL 
            ELSE 0 
        END) AS FACTURATION_REALISEE
FROM CONTRACTS C
INNER JOIN RESERVATIONS R ON C.ID_RESERV = R.ID_RESERV
INNER JOIN FLOTTE F ON R.ID_VEHIC = F.ID_VEHIC
INNER JOIN DISPO_VEHICULE DV ON F.ID_VEHIC = DV.ID_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
GROUP BY 
    A.ID_AGE, A.NOM_AGE, 
    DATENAME(MONTH, C.DATE_DEBUT), 
    YEAR(C.DATE_DEBUT), 
    MONTH(C.DATE_DEBUT)
ORDER BY 
    A.NOM_AGE, 
    YEAR(C.DATE_DEBUT), 
    MONTH(C.DATE_DEBUT)
"""
