# queriesrapports.py

# Liste de tous les véhicules de la flotte, avec état et contrat actif
GET_FLOTTE_VEHICULES = """
SELECT DISTINCT F.ID_VEHIC, MV.MARQUE, MD.MODELE, TV.TYPE_VEHIC, F.TYPE_CARBUR, F.COULEUR, F.ANNEE_FAB, F.IMMATRICULATION, F.KM, F.STATUS AS STATUS_MAINTENANCE,
    COALESCE(
        (SELECT TOP 1 
		'CONTRAT EN COURS' 
         FROM RESERVATIONS R 
         WHERE R.ID_VEHIC = F.ID_VEHIC 
         AND R.STATUS_RESER = 'CONFIRMEE'
         ORDER BY R.DATE_DEBUT DESC),
        'AUCUN CONTRAT ACTIF'
    ) AS STATUS_RESERVATION
FROM FLOTTE F
INNER JOIN MARQUE_VEHIC MV ON F.ID_MARQ = MV.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
INNER JOIN TYPE_VEHIC TV ON F.ID_TP_VEHIC = TV.ID_TP_VEHIC
LEFT JOIN RESERVATIONS R ON F.ID_VEHIC = R.ID_VEHIC
ORDER BY F.ID_VEHIC
"""

# Liste de tous les clients impliqués dans des incidents impactant l'assurance
GET_CLIENTS_AVEC_INCIDENTS_ASSURANCE = """
SELECT DISTINCT CL.NOM, CL.PERMIS_COND, CL.HIST_ACCIDENTS
FROM CONTRACTS C
INNER JOIN RESERVATIONS R ON C.ID_RESERV = R.ID_RESERV
INNER JOIN CLIENTS CL ON R.ID_CLIENT = CL.ID_CLIENT
INNER JOIN INCIDENTS I ON C.ID_CONTRACT = I.ID_CONTRACT
WHERE I.TYPE_INCIDENT <> 'PANNE'
"""

# Liste de tous les véhicules ayant eu des incidents
GET_VEHICULES_AVEC_INCIDENTS = """
SELECT DISTINCT F.ID_VEHIC, MV.MARQUE, MD.MODELE, F.COULEUR, F.KM, F.ANNEE_FAB, COUNT (I.ID_INCIDENT) AS NUM_INCIDENTS
FROM FLOTTE F
INNER JOIN RESERVATIONS R ON F.ID_VEHIC = R.ID_VEHIC
INNER JOIN CONTRACTS C ON R.ID_RESERV = C.ID_RESERV
INNER JOIN INCIDENTS I ON C.ID_CONTRACT = I.ID_CONTRACT
INNER JOIN MARQUE_VEHIC MV ON F.ID_MARQ = MV.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
GROUP BY F.ID_VEHIC, MV.MARQUE, MD.MODELE, F.COULEUR, F.KM, F.ANNEE_FAB
"""

# Quantité de véhicules disponibles par agence selon le type de voiture
GET_VEHICULES_DISPONIBLES_PAR_AGENCE = """
SELECT A.NOM_AGE, TV.TYPE_VEHIC, DV.DISPON_STOCK, COUNT(F.ID_VEHIC) AS QUANTITE
FROM DISPO_VEHICULE DV
INNER JOIN FLOTTE F ON DV.ID_VEHIC = F.ID_VEHIC
INNER JOIN TYPE_VEHIC TV ON F.ID_TP_VEHIC = TV.ID_TP_VEHIC
INNER JOIN AGENCES A ON DV.ID_AGE = A.ID_AGE
WHERE DV.DISPON_STOCK = 'DISPONIBLE'
GROUP BY A.NOM_AGE, TV.TYPE_VEHIC, DV.DISPON_STOCK
ORDER BY A.NOM_AGE
"""

# État d'entretien des véhicules par agence et employé responsable
GET_ENTRETIEN_PAR_AGENCE = """
SELECT A.NOM_AGE, E.NOM, E.POSTE, MV.MODELE, M.TYPE_MAINTEN, M.STATUS_MAINT, CONVERT(DATE, M.DATE_MAINTEN) AS [DATE DEBUT MAINTENCE],
CONVERT(DATE, M.DATE_MAINTEN_FIN) AS [DATE FIN MAINTENCE],
DATEDIFF(DAY, M.DATE_MAINTEN, ISNULL(M.DATE_MAINTEN_FIN, GETDATE()))+1 AS JOUR_EN_REPAR
FROM MAINTENANCE M
INNER JOIN EMPLOYES E ON M.ID_EMP = E.ID_EMP
INNER JOIN AGENCES A ON E.ID_AGE = A.ID_AGE
INNER JOIN FLOTTE F ON M.ID_VEHIC = F.ID_VEHIC
INNER JOIN MODELE_VEHIC MV ON F.ID_MOD = MV.ID_MOD
"""