# Lister toutes les agences
LISTER_AGENCES = """
SELECT ID_AGE, NOM_AGE, VILLE, ADRESSE, TELEPHONE, EMAIL FROM AGENCES ORDER BY ID_AGE;
"""
# Rechercher une agence par nom, ville ou adresse
RECHERCHER_AGENCE = """
SELECT * FROM AGENCES 
WHERE NOM_AGE LIKE ? OR VILLE LIKE ? OR ADRESSE LIKE ?;
"""
# Récupérer une agence par ID
GET_AGENCE_PAR_ID = """
SELECT * FROM AGENCES WHERE ID_AGE = ?;
"""

# Lister tous les employés
LISTER_EMPLOYES = """
SELECT ID_EMP, NAS, NOM, PRENOM, SALAIRE, POSTE, ID_AGE 
FROM EMPLOYES 
ORDER BY NOM;
"""

# Rechercher un employé par NAS ou Nom
RECHERCHER_EMPLOYE = """
SELECT ID_EMP, NAS, NOM, PRENOM, SALAIRE, POSTE, ID_AGE 
FROM EMPLOYES 
WHERE NAS LIKE ? OR NOM LIKE ?
ORDER BY NOM;
"""
# Récupérer une employe par ID
GET_EMPLOYE_PAR_ID = """
SELECT * FROM EMPLOYES WHERE ID_EMP = ?;
"""

# Lister toutes les marques
LISTER_MARQUES = """
SELECT ID_MARQ, MARQUE
FROM MARQUE_VEHIC
ORDER BY MARQUE;
"""

# Récupérer une marque par ID
GET_MARQUE_PAR_ID = """
SELECT ID_MARQ, MARQUE
FROM MARQUE_VEHIC
WHERE ID_MARQ = ?;
"""

# Rechercher une marque par nom (partiel ou complet)
RECHERCHER_MARQUE = """
SELECT ID_MARQ, MARQUE
FROM MARQUE_VEHIC
WHERE MARQUE LIKE ?;
"""

# Récupérer un modèle par ID
GET_MODELE_PAR_ID = """
SELECT * FROM MODELE_VEHIC WHERE ID_MOD = ?;
"""

# Lister tous les modèles
GET_TOUT_MODELES = """
SELECT * FROM MODELE_VEHIC ORDER BY MODELE;
"""

# Rechercher un modèle par nom
RECHERCHER_MODELES = """
SELECT * FROM MODELE_VEHIC WHERE MODELE LIKE ? ORDER BY MODELE;
"""

# Récupérer un optionnel par ID
GET_OPTIONNEL_PAR_ID = """
SELECT * FROM OPTIONNELS WHERE ID_OPTIO = ?;
"""

# Lister tous les optionnels
LISTER_OPTIONNELS = """
SELECT * FROM OPTIONNELS ORDER BY NOM_OPTIO;
"""

# Rechercher un optionnel par nom
RECHERCHER_OPTIONNELS = """
SELECT * FROM OPTIONNELS WHERE NOM_OPTIO LIKE ? ORDER BY NOM_OPTIO;
"""

# Récupérer une maintenance par ID
GET_MAINTENANCE_PAR_ID = """
SELECT * FROM MAINTENANCE WHERE ID_MAINTEN = ?;
"""

# Lister toutes les maintenances
LISTER_MAINTENANCES = """
SELECT * FROM MAINTENANCE;
"""

# Rechercher une maintenance par type ou ID du véhicule
RECHERCHER_MAINTENANCE = """
SELECT * FROM MAINTENANCE
WHERE TYPE_MAINTEN LIKE ? OR (ISNUMERIC(?) = 1 AND ID_VEHIC = ?);
"""

# Requête pour récupérer un véhicule par son ID
GET_VEHICULE_PAR_ID = """
SELECT * FROM FLOTTE WHERE ID_VEHIC = ?;
"""

# Requête pour lister tous les véhicules de la flotte
LISTER_VEHICULES = """
SELECT 
    F.ID_VEHIC, M.MARQUE, MD.MODELE, T.TYPE_VEHIC, F.ANNEE_FAB, 
    F.COULEUR, F.IMMATRICULATION, F.STATUS, F.KM
FROM FLOTTE F
INNER JOIN MARQUE_VEHIC M ON F.ID_MARQ = M.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
INNER JOIN TYPE_VEHIC T ON F.ID_TP_VEHIC = T.ID_TP_VEHIC;
"""

# Requête pour rechercher un véhicule par immatriculation ou modèle
RECHERCHER_VEHICULE = """
SELECT 
    F.ID_VEHIC, M.MARQUE, MD.MODELE, T.TYPE_VEHIC, F.ANNEE_FAB, 
    F.COULEUR, F.IMMATRICULATION, F.STATUS, F.KM
FROM FLOTTE F
INNER JOIN MARQUE_VEHIC M ON F.ID_MARQ = M.ID_MARQ
INNER JOIN MODELE_VEHIC MD ON F.ID_MOD = MD.ID_MOD
INNER JOIN TYPE_VEHIC T ON F.ID_TP_VEHIC = T.ID_TP_VEHIC
WHERE F.IMMATRICULATION LIKE ? OR MD.MODELE LIKE ?;
"""

# Requête pour récupérer une assurance par ID
GET_ASSURANCE_PAR_ID = """
SELECT * FROM ASSURANCE WHERE ID_ASSURANCE = ?;
"""

# Requête pour lister toutes les assurances
LISTER_ASSURANCES = """
SELECT ID_ASSURANCE, TYPE_ASSURANCE, PRIX_JOUR FROM ASSURANCE;
"""

# Requête pour rechercher une assurance par type
RECHERCHER_ASSURANCE = """
SELECT ID_ASSURANCE, TYPE_ASSURANCE, PRIX_JOUR 
FROM ASSURANCE 
WHERE TYPE_ASSURANCE LIKE ?;
"""
